total_buffer_size_mb = 0
concurrency = 8
endpoint = ""
region = ""
local_mode = false
resource_arn = ""
role_arn = ""
no_verify_ssl = false
proxy_address = ""
version = 1

[socket]

udp_address = "127.0.0.1:2000"

[logging]

log_rotation = true
log_level = "prod"
log_path = ""